### PR TITLE
Update dependencies, remove React preset

### PR DESCRIPTION
**Pull request by arkon**
Also removed the `./node_modules/.bin/` path from the npm scripts, since that's automatically in the PATH when running them.

### CODE REVIEW

**Comment by TSedlar** [comment]
While I do agree with removing the react preset and like some of your README changes, removing ./node_modules/.bin/ assumes that you have gulp installed globally.

**Comment by arkon** [comment]
It should use the local version if you're running gulp via an npm script, as it uses locally installed packages before looking for globally installed ones. If you run `npm run build-chrome`, it should still work without the globally installed gulp.

**Comment by TSedlar** [comment]
Ah, didn't know. Another project I worked on.. that author didn't know that as well. TIL. I'll double check things when I get back home and merge the PR.

**Comment by arkon** [comment]
The fact that the Travis build succeeded without having to install gulp globally also verifies this. :)

**Pull request merged**
